export const CREATE_INITIAL_SIGNUP = "CREATE_INITIAL_SIGNUP";
export const CREATE_SUCCESS_SIGNUP = "CREATE_SUCCESS_SIGNUP";
export const CREATE_ERROR_SIGNUP = "CREATE_ERROR_SIGNUP";

export const UPDATE_USER_PRFILE_INITIAL = 'UPDATE_USER_PRFILE_INITIAL';
export const UPDATE_USER_PRFILE_SUCCESS = 'UPDATE_USER_PRFILE_SUCCESS';
export const UPDATE_USER_PRFILE_ERROR  = 'UPDATE_USER_PRFILE_ERROR';

export const CHANGE_USER_PASSWORD_INITIAL = 'CHANGE_USER_PASSWORD_INITIAL';
export const CHANGE_USER_PASSWORD_SUCCESS = 'CHANGE_USER_PASSWORD_SUCCESS';
export const CHANGE_USER_PASSWORD_ERROR = 'CHANGE_USER_PASSWORD_ERROR';

export const CHNAGE_PASSWORD_STATUS = 'CHNAGE_PASSWORD_STATUS';

export const ON_FORM_DISPLAY_INITIAL = 'ON_FORM_DISPLAY_INITIAL';
export const ON_FORM_DISPLAY_SUCCESS = 'ON_FORM_DISPLAY_SUCCESS';
export const ON_FORM_DISPLAY_ERROR = 'ON_FORM_DISPLAY_ERROR';

export const TOKEN_ON_LOGIN = 'TOKEN_ON_LOGIN';

export const LOGED_DATA = 'LOGED_DATA'

export const ADD_CUSTOMER_INITIAL = 'ADD_CUSTOMER_INITIAL';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_ERROR = 'ADD_CUSTOMER_ERROR';

export const ADD_CUSTOMER_SUCCESS_STATUS = 'ADD_CUSTOMER_SUCCESS_STATUS';

export const DISPLAY_CUSTOMER_DATA_INITIAL = 'DISPLAY_CUSTOMER_DATA_INITIAL'; 
export const DISPLAY_CUSTOMER_DATA_SUCCESS = 'DISPLAY_CUSTOMER_DATA_SUCCESS'; 
export const DISPLAY_CUSTOMER_DATA_ERROR = 'DISPLAY_CUSTOMER_DATA_ERROR';

export const DELETE_CUSTOMER_INITIAL = 'DELETE_CUSTOMER_INITIAL';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';

export const UPDATE_CLICKED_DATA = 'UPDATE_CLICKED_DATA';


export const UPDATE_CUSTOMER_INITIAL = 'UPDATE_CUSTOMER_INITIAL';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';

export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

export const ADD_ITEMS_OF_CUSTOMER_INITIAL = 'ADD_ITEMS_OF_CUSTOMER_INITIAL';
export const ADD_ITEMS_OF_CUSTOMER_SUCCESS = 'ADD_ITEMS_OF_CUSTOMER_SUCCESS';
export const ADD_ITEMS_OF_CUSTOMER_ERROR = 'ADD_ITEMS_OF_CUSTOMER_ERROR';

export const GET_ITEMS_OF_CUSTOMER_INITIAL = 'GET_ITEMS_OF_CUSTOMER_INITIAL';
export const GET_ITEMS_OF_CUSTOMER_SUCCESS = 'GET_ITEMS_OF_CUSTOMER_SUCCESS';
export const GET_ITEMS_OF_CUSTOMER_ERROR = 'GET_ITEMS_OF_CUSTOMER_ERROR'

export const ADD_MONEY_OF_CUSTOMER_INITIAL = 'ADD_MONEY_OF_CUSTOMER_INITIAL';
export const ADD_MONEY_OF_CUSTOMER_SUCCESS = 'ADD_MONEY_OF_CUSTOMER_SUCCESS';
export const ADD_MONEY_OF_CUSTOMER_ERROR = 'ADD_MONEY_OF_CUSTOMER_ERROR'

export const GET_MONEY_OF_CUSTOMER_INITIAL =  'GET_MONEY_OF_CUSTOMER_INITIAL';
export const GET_MONEY_OF_CUSTOMER_SUCCESS =  'GET_MONEY_OF_CUSTOMER_SUCCESS';
export const GET_MONEY_OF_CUSTOMER_ERROR =  'GET_MONEY_OF_CUSTOMER_ERROR'

export const SEARCH_TEXT = 'SEARCH_TEXT'